---
# This playbook will install mysql and create db user and give permissions.

- name: password root MySQL
  debconf:
   name: mysql-server
   question: mysql-server/root_password
   value: "danilo20"
   vtype: password

- name: confirm password root MySQL
  debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   value: "danilo20"
   vtype: password

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python-mysqldb

- name: MySQL configuration file
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
    notify:
      -restart mysql

- name: Started Mysql service
  command: service mysql start
  register: start

- name: Create Application Database
  mysql_db:
    login_user: root
    login_password: danilo20
    name: "{{ dbname }}"
    state: present


- name: Create Application DB User
  mysql_user:
    login_user: root
    login_password: danilo20
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
